backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

media_library:
  name: uploadcare
  config:
    publicKey: 0027114e6dd7fb706ded

collections:
  - name: "locations"
    label: "Locations"
    label_singular: "Location"
    format: "json"
    extension: "json"
    delete: false
    editor:
      preview: false
    folder: content/locations
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Cover Image", name: "cover", widget: "image", multiple: false }
      - { label: "Description", name: "description", widget: "string", pattern: [".{,300}", "Must not exceed 300 characters"] }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field: {label: "Tag", name: "tag", widget: "string"}      
      - { label: "Address", name: "website", widget: "string" }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Phone", name: "phone", widget: "string", required: false }
      - { label: "PDF", name: "pdf", widget: "file", required: false, multiple: false }
      - label: "Delivery Hours"
        name: "deliveryHours"
        widget: "list"
        required: false
        field: {label: "Day", name: "tag", widget: "datetime"}    
        